changelog_type: 'commit_message' # or 'pull_request'
header_prefix: 'Version:'
commit_changelog: true
comment_changelog: true
include_unlabeled_changes: true
unlabeled_group_title: 'Unlabeled Changes'
group_config:
  - title: Bug Fixes
    labels:
      - bug
      - bugfix
  - title: Hotfix
    labels:
      - hotfix
  - title: Code Improvements
    labels:
      - improvements
      - enhancement
  - title: New Features
    labels:
      - feature
      - refactoring
  - title: Documentation Updates
    labels:
      - docs
      - documentation
      - doc
  - title: Test
    labels:
      - test